import Footer from "./Footer";
import Menu from "./Menu";

export const metadata = {
  title: "Electrónica",
  description: "Generated by create next app",
};
const ElectronicaLayout = ({ children }) => {
  return (
    <section>
      <Menu />
      {children}
      <Footer />
    </section>
  );
};

export default ElectronicaLayout;
