import Footer from "./Footer";
import Menu from "./Menu";

export const metadata = {
  title: "Contratista",
  description: "Generated by create next app",
};
const Contratistalayout = ({ children }) => {
  return (
    <section>
      <Menu />
      {children}
      <Footer />
    </section>
  );
};

export default Contratistalayout;
